export class ConfigError extends Error {
  constructor(
    public readonly code: string,
    message: string,
    public readonly status: number = 400,
  ) {
    super(message);
    this.name = 'ConfigError';
  }
}

export const ConfigErrorCodes = {
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  CONFIG_ALREADY_EXISTS: 'CONFIG_ALREADY_EXISTS',
  CONFIG_KEY_RESERVED: 'CONFIG_KEY_RESERVED',
  CONFIG_VALIDATION_FAILED: 'CONFIG_VALIDATION_FAILED',
  CONFIG_INVALID_VALUE: 'CONFIG_INVALID_VALUE',
  CONFIG_VALUE_EXPIRED: 'CONFIG_VALUE_EXPIRED',
  CONFIG_RESTRICTED: 'CONFIG_RESTRICTED',
  CONFIG_INHERITANCE_CYCLE: 'CONFIG_INHERITANCE_CYCLE',
  CONFIG_INHERITANCE_DEPTH_EXCEEDED: 'CONFIG_INHERITANCE_DEPTH_EXCEEDED',
  SECRET_NOT_FOUND: 'SECRET_NOT_FOUND',
  SECRET_EXPIRED: 'SECRET_EXPIRED',
  SECRET_COMPROMISED: 'SECRET_COMPROMISED',
  SECRET_UNAUTHORIZED_ACCESS: 'SECRET_UNAUTHORIZED_ACCESS',
  SECRET_ROTATION_FAILED: 'SECRET_ROTATION_FAILED',
  ENVIRONMENT_NOT_FOUND: 'ENVIRONMENT_NOT_FOUND',
  ENVIRONMENT_ALREADY_EXISTS: 'ENVIRONMENT_ALREADY_EXISTS',
  ENVIRONMENT_PROTECTED: 'ENVIRONMENT_PROTECTED',
  ENVIRONMENT_PROMOTION_FAILED: 'ENVIRONMENT_PROMOTION_FAILED',
  FEATURE_FLAG_NOT_FOUND: 'FEATURE_FLAG_NOT_FOUND',
  FEATURE_FLAG_ALREADY_EXISTS: 'FEATURE_FLAG_ALREADY_EXISTS',
  BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',
  BLOCKCHAIN_CONFIG_NOT_FOUND: 'BLOCKCHAIN_CONFIG_NOT_FOUND',
  AI_CONFIG_NOT_FOUND: 'AI_CONFIG_NOT_FOUND',
} as const;

export type ConfigErrorCode = keyof typeof ConfigErrorCodes;