export { ConfigEngineModule } from './presentation/config-engine.module';
export { ConfigService } from './application/config.service';
export { SecretService } from './application/secret.service';
export { FeatureFlagService } from './application/feature-flag.service';
export { EnvironmentService } from './application/environment.service';
export { BrandService } from './application/brand.service';
export { AuditService } from './application/audit.service';
export { ValidationService } from './application/validation.service';
export { InheritanceResolverService } from './application/inheritance-resolver.service';

export type { IConfigRepository } from './domain/config-repository.interface';
export { IConfigRepository as IConfigRepositoryToken } from './domain/config-repository.interface';
export type { ISecretStore } from './domain/secret-store.interface';
export { ISecretStore as ISecretStoreToken } from './domain/secret-store.interface';
export type { IEnvironmentRepository } from './domain/environment-repository.interface';
export { IEnvironmentRepository as IEnvironmentRepositoryToken } from './domain/environment-repository.interface';
export type { IFeatureFlagRepository } from './domain/feature-flag-repository.interface';
export { IFeatureFlagRepository as IFeatureFlagRepositoryToken } from './domain/feature-flag-repository.interface';
export type { IBrandRepository } from './domain/brand-repository.interface';
export { IBrandRepository as IBrandRepositoryToken } from './domain/brand-repository.interface';
export type { IBlockchainConfigRepository } from './domain/brand-repository.interface';
export { IBlockchainConfigRepository as IBlockchainConfigRepositoryToken } from './domain/brand-repository.interface';
export type { IAiConfigRepository } from './domain/brand-repository.interface';
export { IAiConfigRepository as IAiConfigRepositoryToken } from './domain/brand-repository.interface';
export type { IConfigAuditLog } from './domain/config-audit-log.interface';
export { IConfigAuditLog as IConfigAuditLogToken } from './domain/config-audit-log.interface';
export type { IConfigEventEmitter } from './domain/config-event-emitter.interface';
export { IConfigEventEmitter as IConfigEventEmitterToken } from './domain/config-event-emitter.interface';
export type { IConfigWorkflowBridge } from './domain/config-workflow-bridge.interface';
export { IConfigWorkflowBridge as IConfigWorkflowBridgeToken } from './domain/config-workflow-bridge.interface';
export type { IEncryptionService, EncryptedData } from './domain/encryption-service.interface';
export { IEncryptionService as IEncryptionServiceToken } from './domain/encryption-service.interface';
export type { IConfigValidator } from './domain/config-validator.interface';
export { IConfigValidator as IConfigValidatorToken } from './domain/config-validator.interface';
export type { IInheritanceResolver, InheritanceChainItem } from './domain/inheritance-resolver.interface';
export { IInheritanceResolver as IInheritanceResolverToken } from './domain/inheritance-resolver.interface';